[package]
name = "v2ray-heal"
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"


[dependencies]
tokio = { version = "*", features = [
    "net",
    "io-std",
    "io-util",
    "bytes",
    "macros",
    "rt-multi-thread",
] }
futures = { version = "*" }
tokio-util = { version = "*", features = ["compat"] }

pin-project = { version = "*" }

# [lints]
# workspace = true
clap = { version = "*", features = ["derive"] }
anyhow = { version = "*" }
thiserror = { version = "*" }
url = { version = "*" }
config = { version = "*", default-features = false, features = [
    "toml",
    "yaml",
] }
rustls = { version = "*", default-features = false, features = ["std"] }

tracing = { version = "*" }
tracing-subscriber = { version = "*", features = ["env-filter"] }

# for parsing/escaping/unescaping/decoding
nom = { version = "*" }
nom_locate = { version = "*" }

bytes = { version = "*" }
bstr = { version = "*" }
uuid = { version = "*" }
base64 = { version = "*" }
urlencoding = { version = "*" }
escape8259 = { version = "*" }
unescaper = { version = "*" }
chardetng = { version = "*", features = ["multithreading"] }
percent-encoding = { version = "*" }
encoding_rs = { version = "*" }
memchr = { version = "*" }

serde = { version = "*" }
serde_json = { version = "*" }

rapidhash = { version = "*" }

reqwest = { version = "*", features = ["stream"] }
scraper = { version = "*" }
regex = { version = "*" }
yaml-rust2 = { version = "*" }
mimalloc = { version = "*" }
smartstring = { version = "*" }
rayon = { version = "*" }
rustc-hash = { version = "*" }
htmlize = { version = "1.1.0", features = ["entities", "unescape_fast"] }

[dev-dependencies]
